parameters:
    survival_kit.deployment.git_remote: 'origin'
    survival_kit.deployment.git_base_branch: 'master'
    survival_kit.deployment.secret_token: ''

services:
    GuzzleHttp\Client: ~
    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    Leadin\SurvivalKitBundle\Logging\Logger:
        public: true
        tags:
            - { name: !php/const Leadin\SurvivalKitBundle\DependencyInjection\Facade::TAG }

    Leadin\SurvivalKitBundle\DependencyInjection\Facade:
        public: true

    Leadin\SurvivalKitBundle\EventSubscriber\AuthenticationHeaderSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Leadin\SurvivalKitBundle\EventSubscriber\RequestBodySubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClient:
        public: true
        calls:
            - [setHttpClient, ['@GuzzleHttp\Client']]

    Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClientResponse:
        public: true

    Leadin\SurvivalKitBundle\Deployment\Github\PullRequest:
        public: true

    Leadin\SurvivalKitBundle\Deployment\DeploymentCommand:
        public: true
        arguments:
            $parameterBag: '@parameter_bag'

    Leadin\SurvivalKitBundle\Deployment\Github\GithubDeploymentService:
        public: true
        calls:
            - [setDeploymentCommand, ['@Leadin\SurvivalKitBundle\Deployment\DeploymentCommand']]

    Leadin\SurvivalKitBundle\Controller\DeploymentController:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $githubDeploymentService: '@Leadin\SurvivalKitBundle\Deployment\Github\GithubDeploymentService'
        tags:
            - { name: container.service_subscriber }
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    Leadin\SurvivalKitBundle\Controller\DebugManagerController:
        public: true
        tags:
            - { name: container.service_subscriber }
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
