services:
    GuzzleHttp\Client: ~
    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

    Leadin\SurvivalKitBundle\Logging\Logger:
        public: true
        tags:
            - { name: !php/const Leadin\SurvivalKitBundle\DependencyInjection\Facade::TAG }

    Leadin\SurvivalKitBundle\Logging\DebugManagerConfigStorage:
        arguments:
            $configCachePool: '@cache.app'

    Leadin\SurvivalKitBundle\DependencyInjection\Facade:
        public: true

    Leadin\SurvivalKitBundle\EventSubscriber\AuthenticationSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Leadin\SurvivalKitBundle\EventSubscriber\RequestBodySubscriber:
        tags:
            - { name: kernel.event_subscriber }

    Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClient:
        public: true
        calls:
            - [setHttpClient, ['@GuzzleHttp\Client']]

    Leadin\SurvivalKitBundle\Deployment\Github\PullRequest:
        public: true

    Leadin\SurvivalKitBundle\Deployment\DeploymentCommand:
        public: true
        arguments:
            $parameterBag: '@parameter_bag'

    Leadin\SurvivalKitBundle\Deployment\Github\GithubDeploymentService:
        public: true
        calls:
            - [setDeploymentCommand, ['@Leadin\SurvivalKitBundle\Deployment\DeploymentCommand']]

    Leadin\SurvivalKitBundle\Controller\DeploymentController:
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $githubDeploymentService: '@Leadin\SurvivalKitBundle\Deployment\Github\GithubDeploymentService'
        tags:
            - { name: container.service_subscriber }
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    Leadin\SurvivalKitBundle\Controller\DebugManagerController:
        public: true
        arguments:
            $configStorage: '@Leadin\SurvivalKitBundle\Logging\DebugManagerConfigStorage'
        tags:
            - { name: container.service_subscriber }
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    Leadin\SurvivalKitBundle\Controller\InternalToolsController:
        public: true
        tags:
            - { name: container.service_subscriber }
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]

    Leadin\SurvivalKitBundle\Command\OPCacheResetCommand:
        public: true
        arguments:
            $sAppHost: '%survival_kit.app_host%'
            $sAuthorizationToken: '%kernel.secret%'
            $httpClient: '@Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClient'
            $router: '@router.default'
        tags:
            - { name: console.command }

    Leadin\SurvivalKitBundle\EventSubscriber\MaintenaceModeSubscriber:
        arguments:
            $parameterBag: '@parameter_bag'
            $twig: '@twig'
        tags:
            - { name: kernel.event_subscriber }
