parameters:
    # nothing to declare

services:
    Leadin\SurvivalKitBundle\Logging\Logger:
        autoconfigure: true
        public: true

    Leadin\SurvivalKitBundle\DependencyInjection\Facade:
        public: true

    Leadin\SurvivalKitBundle\EventSubscriber\AuthenticationHeaderSubscriber:
        public: true
        tags:
            - { name: kernel.event_subscriber }

    Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClient:
        public: true
        autowire: true

    Leadin\SurvivalKitBundle\HttpHelper\HttpClientHelper\HttpClientResponse:
        public: true
